# Generated by Django 5.1.7 on 2025-03-11 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
                (
                    "created_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 3, 11, 6, 6, 18, 44249, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
